title: Site

tabs:
  pages:
    label: Pages
    sections:
      pages:
        type: pages
        label: Pages
        layout: list

  info:
    label: Info Panel
    fields:
      tagline:
        type: text
        label: Tagline

      info:
        type: layout
        label: Info content
        layouts:
          - '1/1'
        fieldsets:
          - heading
          - text
          - link
